// Generated by CoffeeScript 1.3.3
(function() {

  chrome.browserAction.onClicked.addListener(function(tab) {
    chrome.tabs.executeScript(null, {
      file: "vendor/jquery-1.7.2.min.js"
    });
    chrome.tabs.executeScript(null, {
      file: "vendor/color-0.4.1.js"
    });
    chrome.tabs.executeScript(null, {
      file: "vendor/farbtastic.js"
    });
    chrome.tabs.insertCSS(null, {
      file: "vendor/farbtastic.css"
    });
    return chrome.tabs.executeScript(null, {
      file: "jsColorUnblinder.js"
    });
  });

}).call(this);
