// Generated by CoffeeScript 1.3.3
(function() {
  var ColorPicker, ColorSwapper, ColorUnblinder;

  window.jsCU = {};

  jsCU.wrong_color = "rgb(248, 74, 6)";

  jsCU.right_color = "rgb(0, 128, 0)";

  jsCU.addJavascript = function(jsname, pos) {
    var s, th;
    th = document.getElementsByTagName(pos)[0];
    s = document.createElement('script');
    s.setAttribute('type', 'text/javascript');
    s.setAttribute('src', jsname);
    return th.appendChild(s);
  };

  jsCU.addStylesheet = function(cssname, pos) {
    var s, th;
    th = document.getElementsByTagName(pos)[0];
    s = document.createElement('link');
    s.setAttribute('type', 'text/css');
    s.setAttribute('rel', 'stylesheet');
    s.setAttribute('href', cssname);
    return th.appendChild(s);
  };

  ColorSwapper = (function() {

    function ColorSwapper(conflict_color) {
      this.conflict_color = conflict_color;
      this.conflictive_elements = this.findByColor(this.conflict_color);
    }

    ColorSwapper.prototype.change_with = function(new_color) {
      var rgbColor;
      rgbColor = "" + (Color(new_color).rgbString());
      return this.changeColors(rgbColor);
    };

    ColorSwapper.prototype.findByColor = function(color) {
      return $("*").filter(function() {
        return $(this).css('color') === color;
      });
    };

    ColorSwapper.prototype.changeColors = function(color) {
      return this.conflictive_elements.css('color', color);
    };

    return ColorSwapper;

  })();

  ColorPicker = (function() {

    function ColorPicker() {
      this.addPlaceholder();
      this.addJS();
      this.addCSS();
    }

    ColorPicker.prototype.start = function(callback) {
      return this._startWhenReady(callback);
    };

    ColorPicker.prototype._startWhenReady = function(callback) {
      var tryAgain,
        _this = this;
      if (typeof $.farbtastic !== 'undefined') {
        return $('#colorpicker').farbtastic(callback);
      } else {
        tryAgain = function() {
          return _this._startWhenReady(callback);
        };
        return setTimeout(tryAgain, 100);
      }
    };

    ColorPicker.prototype.addPlaceholder = function() {
      var div;
      div = $("<div id='colorpicker'></div>");
      div.css({
        position: 'absolute',
        top: '50px',
        right: '50px'
      });
      return $("body").append(div);
    };

    ColorPicker.prototype.addJS = function() {
      return jsCU.addJavascript('../vendor/farbtastic/farbtastic.js', 'body');
    };

    ColorPicker.prototype.addCSS = function() {
      return jsCU.addStylesheet('../vendor/farbtastic/farbtastic.css', 'body');
    };

    return ColorPicker;

  })();

  ColorUnblinder = (function() {

    function ColorUnblinder() {
      var _this = this;
      this.addColorLibrary();
      this.picker = new ColorPicker();
      this.swapper = new ColorSwapper(jsCU.wrong_color);
      this.picker.start(function(color) {
        return _this.changer(color);
      });
    }

    ColorUnblinder.prototype.changer = function(color) {
      return this.swapper.change_with(color);
    };

    ColorUnblinder.prototype.addColorLibrary = function() {
      return jsCU.addJavascript('../vendor/color-0.4.1.js', 'body');
    };

    return ColorUnblinder;

  })();

  window.CU = ColorUnblinder;

}).call(this);
